language: python

matrix:
  include:
  - python: 2.7
  - python: 3.6
#  - python: 3.7
#    sudo: required
#    dist: xenial

#before_install:

install:
  - pip install -r requirements.txt
  - pip install -e .
  - wget --user=HITRAN --password=getdata -N https://www.cfa.harvard.edu/HITRAN/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/01_hit12.zip && unzip 01_hit12.zip -d ./pyratbay/tests
  - cd /home/travis/build/pcubillos/pyratbay && make

script: pytest
